### ISSUE TITLE
Version 0.51.2 broke tributejs usage.

### ISSUE THREAD

**Issue by raivil** [stimulus-use/stimulus-use#295]
Hi,

Upgrading to version `0.51.2` broke some features based on `tributejs`.

The change from https://github.com/stimulus-use/stimulus-use/pull/252 (`useDispatch: Fix params for debounced actions if event is shared `) seems to be the cause.

I've opened an issue on Tributejs as well at https://github.com/zurb/tribute/issues/892

The current error is: 
```
index.js:979 Uncaught TypeError: Cannot create property 'params' on string '/user/mentions'
    at index.js:979:47
    at Array.forEach (<anonymous>)
    at s (index.js:979:18)
```

**Comment by raivil** [comment]
Hey @marcoroth 
Sorry but it will be a little hard to post everything, the code is protected and it's also generated by other components, which makes it a little bit more complex.

**Comment by weaverryan** [comment]
Hi!

Here is a reproducer: https://jsfiddle.net/gyjfxs27/6/

Unless I'm missing something, `useDebounce` seems quite broken. It seems that you HAVE to pass an object with a `params` key now when calling a debounced method.

Does that help? Is that bug, or am I misunderstanding the proper use?

Thanks!

**Comment by mepatterson** [comment]
Any news on this? `useDebounce` is one of my favorites in this library and just hit this same error...

**Comment by marcoroth** [comment]
I just got into my first work-week after RailsConf. I'm trying to take a look this week. Thanks for your patience!

**Comment by endelwar** [comment]
Hi @marcoroth, have you had time to look at this issue?

**Comment by endelwar** [comment]
Any update on this?
